name: Release

on:
  push:
    branches: [ master ]

env:
  PRIMARY_MAVEN_MODULE: ${{ github.event.repository.name }}

permissions:
  contents: write
  pull-requests: write

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
      
    - name: Build with Maven
      run: ./mvnw -B clean package
      
    - name: Check for uncommited changes
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          echo ----------------------------------------
          echo git status
          echo ----------------------------------------
          git status
          echo ----------------------------------------
          echo git diff
          echo ----------------------------------------
          git diff
          echo ----------------------------------------
          echo Troubleshooting
          echo ----------------------------------------
          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && ./mvnw -B clean package"
          exit 1
        fi

  prepare-release:
    runs-on: ubuntu-latest
    needs: [check-code]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4
      
    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
  
    - name: Un-SNAP 
      run: |
        mvnwPath=$(readlink -f ./mvnw)
        modules=("") # root
        modules+=($(grep -ozP '(?<=module>)[^<]+' 'pom.xml' | tr -d '\0'))
        for i in "${modules[@]}"
        do
            echo "Processing $i/pom.xml"
            (cd "$i" && $mvnwPath -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false)
        done
  
    - name: Get version
      id: version
      run: |
        version=$(../mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "release=$version" >> $GITHUB_OUTPUT
        echo "releasenumber=${version//[!0-9]/}" >> $GITHUB_OUTPUT
      working-directory: ${{ env.PRIMARY_MAVEN_MODULE }}
  
    - name: Commit and Push
      run: |
        git add -A
        git commit -m "Release ${{ steps.version.outputs.release }}"
        git push origin
        git tag v${{ steps.version.outputs.release }}
        git push origin --tags
    
    - name: Create Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      with:
        tag_name: v${{ steps.version.outputs.release }}
        release_name: v${{ steps.version.outputs.release }}
        commitish: master
        body: |
          ## [Changelog](https://github.com/${{ github.repository }}/blob/develop/CHANGELOG.md#${{ steps.version.outputs.releasenumber }})
          See [Changelog#v${{ steps.version.outputs.release }}](https://github.com/${{ github.repository }}/blob/develop/CHANGELOG.md#${{ steps.version.outputs.releasenumber }}) for more information.

          ## Installation
          Download the javaagent from the assets section below and [attach it to your java application](https://github.com/xdev-software/thread-origin-agent#usage).

  publish-assets:
    runs-on: ubuntu-latest
    needs: [prepare-release]
    steps:
    - uses: actions/checkout@v4
    
    - name: Init Git and pull
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build
      run: ../mvnw -B clean package
      working-directory: ${{ env.PRIMARY_MAVEN_MODULE }}

    - name: Upload Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.prepare_release.outputs.upload_url }}
        asset_path: ${{ env.PRIMARY_MAVEN_MODULE }}/target/${{ env.PRIMARY_MAVEN_MODULE }}-*.jar

  publish-pages:
    runs-on: ubuntu-latest
    needs: [prepare-release]
    steps:
    - uses: actions/checkout@v4
      
    - name: Init Git and pull
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull

    - name: Setup - Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build site
      run: ../mvnw -B site
      working-directory: ${{ env.PRIMARY_MAVEN_MODULE }}

    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./${{ env.PRIMARY_MAVEN_MODULE }}/target/site

  after-release:
    runs-on: ubuntu-latest
    needs: [publish-assets]
    steps:
    - uses: actions/checkout@v4
      
    - name: Init Git and pull
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull

    - name: Inc Version and SNAP 
      run: |
        mvnwPath=$(readlink -f ./mvnw)
        modules=("") # root
        modules+=($(grep -ozP '(?<=module>)[^<]+' 'pom.xml' | tr -d '\0'))
        for i in "${modules[@]}"
        do
            echo "Processing $i/pom.xml"
            (cd "$i" && $mvnwPath -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false -DnextSnapshot=true)
        done

    - name: Git Commit and Push
      run: |
        git add -A
        git commit -m "Preparing for next development iteration"
        git push origin
    
    - name: pull-request
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh_pr_up() { 
          gh pr create "$@" || gh pr edit "$@" 
        }
        gh_pr_up -B "develop" \
          --title "Sync back" \
          --body "An automated PR to sync changes back"
